### ISSUE TITLE
Use Browserify

### ISSUE THREAD

**Issue by jonnyhaynes** [powerhouse-industries/front-end-starter#4]
Possible upgrade to utilise modular JS and node dependancies better on the front end. Probably needs a branch as it's such a big change.

> `require('modules')` in the browser
> 
> Use a [node](http://nodejs.org)-style `require()` to organize your browser code and load modules installed by [npm](https://www.npmjs.com).
> 
> browserify will recursively analyze all the `require()` calls in your app in order to build a bundle you can serve up to the browser in a single `<script>` tag.

**Comment by jonnyhaynes** [comment]
After discussing with @oliverfarrell, we had reservations about keeping things up to date if we were to swap bower for node modules and browserify. Most of the bower modules are on NPM, see below:
- [npm install fastclick](https://www.npmjs.com/package/fastclick)
- [npm install flickity](https://www.npmjs.com/package/flickity)
- [npm install lazysizes](https://www.npmjs.com/package/lazysizes)
- [npm install modernizr](https://www.npmjs.com/package/modernizr)
- [npm install picturefill](https://www.npmjs.com/package/picturefill)
- [npm install placeholder](https://www.npmjs.com/package/placeholder)

Things that aren't:
- [matchMedia](https://github.com/weblinc/media-match)*

*This is a piece of code that hasn't changed in 3 years as it's designed to support older browsers. I think we're safe to run with this as a static file. N.B. It's also only required for IE8 I think, support for that will be ditched soon anyway.

Things that are ours and can be converted to NPM:
- [checkmq](https://github.com/jonnyhaynes/checkmq)
- [cookie-disclaimer](https://github.com/jonnyhaynes/cookie-disclaimer)
- [inline-svg](https://github.com/jonnyhaynes/inline-svg)

**Comment by oliverfarrell** [comment]
Looks like this could be a winner then. Chuck it on a branch and see where we get. It would be nice if we could do it this way and remove the concatenation from the bash script and let Browserify do all that. It's always felt a little dirty doing it that way.

**Comment by jonnyhaynes** [comment]
I've converted the three things that we control to Node.js modules. Next step, work on the browserify stuff.

**Comment by oliverfarrell** [comment]
@jonnyhaynes  This is now done. It's on a branch `feature/browserify-implementation` if you could take a look and make sure everything looks good.

**Comment by oliverfarrell** [comment]
Merged.
